#!/bin/csh

if ($#argv == 1) root -l -b -q CompilePtRelAnalyzer.C

setenv WORKINGDIRECTORY $PWD

setenv TEMPLATEVARIABLE 'PtRel' 
#setenv TEMPLATEVARIABLE 'System8'  

setenv PUWEIGHTING '_PSRun20182018Ultimate'

setenv KINWEIGHTING ''
#setenv KINWEIGHTING '_KinPtBinsCentral'

#setenv SELECTION ''
#setenv SELECTION '_TrgEmul'
setenv SELECTION '_TrgConf'

setenv DATARANGEINDEX '-999'

mkdir -p Weights/PileUp
mkdir -p Templates
mkdir -p Templates/Histograms

mkdir -p JobOutput
cd JobOutput/

#setenv MACRONAME 'EventCounterQCDMuQCDX'
setenv MACRONAME 'EventCounterQCDX' 
#bsub -q cmscaf1nd -J "$MACRONAME" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
 
setenv MACRONAME 'ProduceHistogramsBTagMu'
#bsub -q cmscaf1nd -J "$MACRONAME[1-4]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ProduceHistogramsQCDMu'
#bsub -q cmscaf1nd -J "$MACRONAME[1-12]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
 
setenv MACRONAME 'ProduceLightHistogramsJetHT'
#bsub -q cmscaf1nd -J "$MACRONAME[1-4]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ProduceLightHistogramsQCD'
#bsub -q cmscaf1nd -J "$MACRONAME[1-13]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX

setenv MACRONAME 'ComputePileUpWeightsLoopBTagMu'
#bsub -q cmscaf1nd -J "$MACRONAME[1-4]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsMergeBTagMu'
#bsub -q cmscaf1nd -J "$MACRONAME" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsLoopQCDMu'
#bsub -q cmscaf1nd -J "$MACRONAME[1-12]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsMergeQCDMu'
#bsub -q cmscaf1nd -J "$MACRONAME" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX

setenv MACRONAME 'ComputePileUpWeightsLoopJetHT'
#bsub -q cmscaf1nd -J "$MACRONAME[1-4]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsMergeJetHT'
#bsub -q cmscaf1nd -J "$MACRONAME" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsLoopQCDX'
#bsub -q cmscaf1nd -J "$MACRONAME[1-13]" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX
setenv MACRONAME 'ComputePileUpWeightsMergeQCDX'
#bsub -q cmscaf1nd -J "$MACRONAME" $WORKINGDIRECTORY/RunPtRelAnalyzer.sh WORKINGDIRECTORY TEMPLATEVARIABLE PUWEIGHTING KINWEIGHTING MACRONAME SELECTION DATARANGEINDEX

cd ../
   
